---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: google
  labels: web
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: google
  template:
    metadata:
      name: google
      labels:
        app: google
    spec:
      containers:
        - name: google
          image: nginx
          ports:
            - containerPort: 80
            
---
apiVersion: v1
kind: Service
metadata:
  name: google
  labels: web
spec:
  selector:
    app: google
  ports:
    - port: 80
      targetPort: 
  
