apiVersion: apps/v1
kind: Deployment
metadata:
  name: mybooks
  labels: 
    app: mybooks
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mybooks
  template:
    metadata:
      name: mybooks
      labels:
        app: mybooks
    spec: 
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_USER
          value: user
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_DB
          value: booksdb
        ports:
        - containerPort: 5432
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 700m
            memory: 1000Mi

---
apiVersion: v1
kind: Service
metadata:
  name: mybooks
  labels: 
    app: mybooks
spec: 
  type: ClusterIP
  ports:
  - port: 5432
    protocol: TCP
  
  
