apiVersion: apps/v1
kind: Deployment
metadata:
  name: booksservice
  labels: 
    app: booksservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: booksservice
  template:
    metadata:
      name: booksservice
      labels:
        app: booksservice
    spec: 
      containers:
      - name: postgres
        image: shaikkhajaibrahim/libbookssvc:1.0
        env:
        - name: DATABASE_URL
          value:  "postgresql://user:password@books-db:5432/booksdb"
        - name: SECRET_KEY
          value: "YtDEVWnL35aAIP-5yxeLjAZ49R920-mMNDfwPyWULu63HFsYzo0f-LO2InxC8eu428k"
        ports:
        - containerPort: 5432
          protocol: TCP
        resources:
          requests:
            cpu: 200m
            memory: 300Mi
          limits:
            cpu: 900m
            memory: 1000Mi

---
apiVersion: v1
kind: Service
metadata:
  name: booksservice
  labels: 
    app: mbooksservice
spec: 
  type: ClusterIP
  ports:
  - port: 5432
    protocol: TCP
  
  

        