apiVersion: apps/v1
kind: Deployment
metadata:
  name: mybooks
  labels: 
    app: mybooks
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mybooks
  template:
    metadata:
      name: mybooks
      labels:
        app: mybooks
    spec: 
      containers:
      - name: postgres
        image: shaikkhajaibrahim/libwebstore:1.0
        env:
        - name: REACT_APP_BACKEND_API_URL
          value: http://user-svc:8000/api/v1
        - name: REACT_APP_BOOKS_API_URL
          value: http://books-svc:8000/api/v1/books
        - name: REACT_APP_USERS_API_URL
          value: http://user-svc:8000/api/v1/users
        ports:
        - containerPort: 5432
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 700m
            memory: 1000Mi

---
apiVersion: v1
kind: Service
metadata:
  name: mybooks
  labels: 
    app: mybooks
spec: 
  type: ClusterIP
  ports:
  - port: 5432
    protocol: TCP
  
  
